# Generated by Django 5.1.3 on 2024-12-18 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0024_clientcontact_created_at_contact_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='clientcontact',
            name='terms_is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='TermPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.term')),
            ],
        ),
    ]
