# Generated by Django 5.1.3 on 2024-12-19 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0025_term_clientcontact_terms_is_active_termpoint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientcontact',
            old_name='name',
            new_name='first_name',
        ),
    ]
