# Generated by Django 5.1.3 on 2024-12-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0026_rename_name_clientcontact_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
