# Generated by Django 5.1.3 on 2025-02-16 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0027_services_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='media1_icon',
            field=models.CharField(blank=True, default='bi bi-cloud-download-fill', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='media2_icon',
            field=models.CharField(blank=True, default='bi bi-cloud-download-fill', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='media3_icon',
            field=models.CharField(blank=True, default='bi bi-cloud-download-fill', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='media4_icon',
            field=models.CharField(blank=True, default='bi bi-cloud-download-fill', max_length=200, null=True),
        ),
    ]
