# Generated by Django 5.1.3 on 2025-02-19 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0030_faqsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_about', to='general.about')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
