# Generated by Django 5.1.3 on 2025-02-19 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0031_textabout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='description',
        ),
    ]
