# Generated by Django 5.1.3 on 2025-02-23 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0033_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='button_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientcontact',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True),
        ),
    ]
